### ISSUE TITLE
Some images are not being displayed in the gallery

### ISSUE THREAD

**Issue by alejost848** [supachailllpay/photo-gallery#12]
I'm experiencing a weird problem with a few images that are not being displayed, like [this one](https://firebasestorage.googleapis.com/v0/b/alejost848-afea9.appspot.com/o/works%2F2-hearts%2F2hearts%20(0%3B00%3B46%3B26).jpg?alt=media&token=26883e59-e6ee-48b0-940c-f70effe53f60). They don't show up in the gallery, but when you open them in the viewer they do appear.

I started debugging the code and found [the line where the image is set](https://github.com/supachailllpay/photo-gallery/blob/master/photo-gallery.html#L170). 

```javascript
item.style.backgroundImage = `url(${url})`
```

It turns out that if you add quotes around the url variable, the problem is gone and the images display correctly. Like this:
```javascript
item.style.backgroundImage = `url("${url}")`
```

Do you know why this happens? Is it safe to create a pull request to address this?

Thanks.

**Comment by supachailllpay** [comment]
Hi @alejost848 good job 👍 

I think the problem is the url contains `(`, `)` characters which if you escape them with `%28` and `%29` respectively like [this one](https://firebasestorage.googleapis.com/v0/b/alejost848-afea9.appspot.com/o/works%2F2-hearts%2F2hearts%20%280%3B00%3B46%3B26%29.jpg?alt=media&token=26883e59-e6ee-48b0-940c-f70effe53f60) should works fine. Anyway It seems normal url encode function (like `encodeURI`) not handle these characters so I think we should handle this case.

Yes, a pull request would be appreciated.

Thanks
